webtalk_init -webtalk_dir /zhome/66/2/168935/uni/digital_systems/PWF/PWF.sim/sim_1/behav/xsim/xsim.dir/PWF_testbench_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Tue May  9 22:46:46 2023" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2258646" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "176339219_1777488102_210753852_502" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "1f736ff0-b88b-45d9-845c-3400afb2451e" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "dc1adf7c80584e4da52664d6e5a4c0b9" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "60" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Scientific" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Scientific Linux release 7.9 (Nitrogen)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2599.841 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "2" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "134.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key File_Counter -value "53" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xelab" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Vhdl2008 -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key GenDLL -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key SDFModeling -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key HWCosim -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key DPI_Used -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Debug -value "typical" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Simulation_Image_Code -value "524 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Image_Data -value "46 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Nets -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Processes -value "576" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Instances -value "588" -context "xsim\\usage"
webtalk_add_data -client xsim -key Xilinx_HDL_Libraries_Used -value "secureip " -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Time -value "3.68_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Memory -value "477028_KB" -context "xsim\\usage"
webtalk_transmit -clientid 918225408 -regid "176339219_1777488102_210753852_502" -xml /zhome/66/2/168935/uni/digital_systems/PWF/PWF.sim/sim_1/behav/xsim/xsim.dir/PWF_testbench_behav/webtalk/usage_statistics_ext_xsim.xml -html /zhome/66/2/168935/uni/digital_systems/PWF/PWF.sim/sim_1/behav/xsim/xsim.dir/PWF_testbench_behav/webtalk/usage_statistics_ext_xsim.html -wdm /zhome/66/2/168935/uni/digital_systems/PWF/PWF.sim/sim_1/behav/xsim/xsim.dir/PWF_testbench_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
